DROP TABLE IF EXISTS PlantList;
DROP TABLE IF EXISTS PlantColors;
DROP TABLE IF EXISTS PlantTypes;
DROP TABLE IF EXISTS SunlightTolerance;
DROP TABLE IF EXISTS Allelopathy;
DROP TABLE IF EXISTS ClimateTypes;
DROP TABLE IF EXISTS Plants;
